my_blog/article/urls.py
from django.urls import path
from . import views

# namespace
app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<str:id>/', views.article_detail, name='article_detail'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls')),
    path('', views.index, name='index'),
]

my_blog/article/models.py
from time import time
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title
    

my_blog/article/views.py
from django.shortcuts import render
from .models import ArticlePost
import markdown
# Create your views here.
def article_list(request):
    articles = ArticlePost.objects.all()
    context = {'articles': articles}
    return render(request, 'article/list.html', context)

def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    article.body = markdown.markdown(article.body,
    extensions=[
        'markdown.extensions.extra', 
        'markdown.extensions.codehilite',
        'markdown.extensions.fenced_code',
        # 'markdown.extensions.tables',
        ])
    context = {'article':article}
    return render(request,'article/detail.html', context)

my_blog/my_blog/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

my_blog/article/templates/article/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 文章详情 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-12 alert alert-success">作者：{{ article.author }}</div>
        <!-- 文章正文 -->
        <div class="col-12">
            <p>{{ article.body | safe }}</p>
        </div>
    </div>
</div>
{% endblock content %}

my_blog/article/templates/article/list.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}首页{% endblock title %} 
{% block content %}
<div class="container">
  <div class="row mt-2">
    {% for article in articles %}
    <div class="col-4 mb-4">
      <div class="card h-100">
        <h4 class="card-header">{{article.title}}</h4>
        <div class="card-body">
          <p class="card-text">{{article.body|slice:'100'}}...</p>
        </div>
        <!--注脚-->
        <div class="card-footer">
          <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

my_blog/article/templates/base.html
{% load static %}
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/material.css' %}">
</head>
<body>
    {% include 'header.html' %}

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}
    
    <!-- 引入 jquery 和 popper -->
    <script src="{% static 'jquery/jquery-3.6.0.js' %}"></script>
    <!-- 
        popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
        在实际的开发中推荐静态文件尽量都使用 cdn 的形式。 
        教程采用本地引入是为了让读者了解静态文件本地部署的流程。
    -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

my_blog/article/templates/footer.html
{% load static %}
<!--Footer-->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; westsea.tech 2022
            <br>
            <a href="https://beian.miit.gov.cn/" target="_blank">京ICP备2022005774号-1</a>
        </p>
        
    </div>
</footer>

my_blog/article/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <!--导航栏商标-->
    <a class="navbar-brand" href="#">My Blog</a>

    <!--导航入口-->
    <div>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

my_blog/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>阳光下的奔跑</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'index/default.css' %}" />
    <link id="theme-style" rel="stylesheet" href="" />
  </head>
  <body>
    <section class="s1">
      <div class="main-container">
        <div class="greeting-wrapper">
          <h1>Hi, I'm Shi Hongji</h1>
        </div>
        <div class="intro-wrapper">
          <div class="nav-wrapper">
            <div class="dots-wrapper">
              <div id="dot-1" class="browser-dot"></div>
              <div id="dot-2" class="browser-dot"></div>
              <div id="dot-3" class="browser-dot"></div>
            </div>
            <ul id="navigation">
              <li><a href="#">Contact</a></li>
              <li><a href="#">Contact</a></li>
            </ul>
          </div>
          <div class="left-column">
            <img id="profile_pic" src="{% static 'index/images/SHJ.JPG' %}" />
            <h5 style="text-align: center; line-height: 0">
              Personalize Theme
            </h5>

            <div id="theme-option-wrapper">
              <div data-mode="light" id="light-mode" class="theme-dot"></div>
              <div data-mode="blue" id="blue-mode" class="theme-dot"></div>
              <div data-mode="green" id="green-mode" class="theme-dot"></div>
              <div data-mode="purple" id="purple-mode" class="theme-dot"></div>
            </div>

            <p id="settings-note">
              Theme settings will be saved for <br />your next visit
            </p>
          </div>
          <div class="right-column">
            <div id="preview-shadow">
              <div id="preview">
                <div id="corner-tl" class="corner"></div>
                <div id="corner-tr" class="corner"></div>
                <h3>What I Do</h3>
                <p>Now I am working as marketer in BHMC. I supply my coding skill to my marketing work.</p>
                <div id="corner-br" class="corner"></div>
                <div id="corner-bl" class="corner"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="s2">
      <div class="main-container">
        <div class="about-wrapper">
          <div class="about-me">
            <h4>More about me</h4>
            <p>
              I like to code but I don't have much time since I work as a
              marketer
            </p>
            <p>
              While I keep busy doing my job, I still wait for a coder
              interview.
            </p>

            <hr />
            <h4>TOP EXPERIENCE</h4>
            <p>
              Fullstack developer with primary focus on Django + React:
              <a target="_blank" href="Resume.pdf">Download Resume</a>
            </p>

            <div id="skills">
              <ul>
                <li>Python</li>
                <li>Django</li>
                <li>JavaScript</li>
                <li>React</li>
                <li>Java</li>
              </ul>
              <ul>
                <li>Google Maps API</li>
                <li>JS Charts</li>
                <li>AMS</li>
                <li>Heroku</li>
                <li>HTML/CSS</li>
              </ul>
            </div>
          </div>
          <div class="social-links">
            <img id="social_img" src="{% static 'index/images/follow.png' %}" />
            <h3>Find me on Twitter & Youtube</h3>
            <a target="_blank" href="">Twitter: @Sheric</a>
            <br />
            <a target="_blank" href="">Youtube: @Shihongji21</a>
          </div>
        </div>
      </div>
    </section>

    <section class="s1">
      <div class="main-container">
        <h3 style="text-align: center">Some of my past projects</h3>
        <div class="post-wrapper">
          <div>
            <div class="post">
              <img class="thumbnail" src="images/SHJ.JPG" />
              <div class="post-preview">
                <h6 class="post-title">Post Title</h6>
                <p class="post-intro">
                  This is a sentence. Some more text here.This is a sentence.
                  Some more text here.This is a sentence. Some more text here.
                </p>
                <a style="font-size: 14px" href="#">Read More</a>
              </div>
            </div>
          </div>
          <div>
            <div class="post">
              <img class="thumbnail" src="images/SHJ.JPG" />
              <div class="post-preview">
                <h6 class="post-title">Post Title</h6>
                <p class="post-intro">
                  This is a sentence. Some more text here.
                </p>
                <a style="font-size: 14px" href="#">Read More</a>
              </div>
            </div>
          </div>
          <div>
            <div class="post">
              <img class="thumbnail" src="images/SHJ.JPG" />
              <div class="post-preview">
                <h6 class="post-title">Post Title</h6>
                <p class="post-intro">
                  This is a sentence. Some more text here.
                </p>
                <a style="font-size: 14px" href="#">Read More</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="s2">
      <div class="main-container">
        <h3 style="text-align: center;">Get In Touch</h3>
        <form id="contact-form">
          <label>Name</label>
          <input type="text" name="name" class="input-field">
          <label>Subject</label>
          <input type="text" name="subject" class="input-field">
          <label>Email</label>
          <input type="text" name="email" class="input-field">
          <label>Message</label>
          <textarea name="message" class="input-field"></textarea>

          <input type="submit" value="Send" id="submit-btn">
        </form>
      </div>
    </section>
    <div>
      <p class="foot_p">
        Designed & Powerd by Shihongji 
        <br>
        Copyright© 2009-2022 Shihongji 阳光下的奔跑
        <br>
        <a href="https://beian.miit.gov.cn/" target="_blank">京ICP备2022005774号-1</a>
      </p>
    
  </div>
    {% comment %} <script type="text/javascript" src="{% static 'index/script.js' %}"> var a ="{% static 'index/blue.css' %}";</script> {% endcomment %}
    <script>
      let theme = localStorage.getItem('theme')
if(theme == null){
    setTheme('light')
} else {
    setTheme(theme)
}
let themeDots = document.getElementsByClassName("theme-dot")

for (let i = 0; i < themeDots.length; i++) {
    themeDots[i].addEventListener('click', function(){
        let mode = this.dataset.mode
        console.log('Option clicked: ', mode)
        setTheme(mode)
    })
}

function setTheme(mode){
    if(mode== 'light'){
        document.getElementById('theme-style').href = "{% static 'index/default.css' %}"
    }
    if(mode== 'blue'){
        document.getElementById('theme-style').href = "{% static 'index/blue.css' %}"
    }
    if(mode== 'green'){
        document.getElementById('theme-style').href = "{% static 'index/green.css' %}"
    }
    if(mode== 'purple'){
        document.getElementById('theme-style').href = "{% static 'index/purple.css' %}"
    }
    localStorage.setItem('theme', mode)
}
    </script>
  </body>
</html>